language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davisdavis27french/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davisdavis27french/docker-react npm run test
